name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if ! command -v go &> /dev/null
          then
            echo "Go no está instalado. Instalando Go..."
            sudo apt-get update
            sudo apt-get install -y wget tar git
            wget https://golang.org/dl/go1.23.3.linux-amd64.tar.gz
            sudo tar -C /usr/local -xvzf go1.23.3.linux-amd64.tar.gz
            echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.bashrc
            source ~/.bashrc
          fi
          pkill -f main.go || echo "No existing process found"
          cd PracticeEC2_OF_GO
          git pull origin main
          nohup go run main.go > output.log 2>&1 &
          echo "Application is running in the background."
